### ISSUE TITLE
404 Not Found when handling a request on a sub-router mounted at a root path (/)

### ISSUE THREAD

**Issue by davidafsilva** [vert-x3/vertx-health-check#40] opened 2022-06-02 15:10 UTC
### Version
[3.9.13](https://github.com/vert-x3/vertx-health-check/tree/3.9.13)
~Haven't tested on 4.x.~ ([tested](https://github.com/vert-x3/vertx-health-check/issues/40#issuecomment-1146649337))

### Context
The full context as well as a reproducer is available at [davidafsilva/vertx-health-checks-404](https://github.com/davidafsilva/vertx-health-checks-404). Please refer to its [README.md](https://github.com/davidafsilva/vertx-health-checks-404/blob/main/README.md) file.

One thing that it lacks though, is our use-case that lead to this, i.e. why we have this sort-of of setup. 
Basically most of our APIs that rely on Vert.x are based on [vertx-web-api-contract](https://github.com/vert-x3/vertx-web/tree/master/vertx-web-api-contract) where we create a router with everything that is defined within the OpenAPI specification, which includes an health endpoint. Next to it we may define other router(s) that provide additional functionality, e.g. dev tooling, that is not part of the _"public API"_.
The way we glue everything together is by creating a root router that mounts the above routers as sub-routers. The _"public API"_ router is usually mounted at `/`.

Please let me know if you need more information and/or if we are doing it wrong and it's not actually a bug.

Grazie!

**Comment by gaol** [comment] 2022-06-03 05:49
It sounds like the issue of https://github.com/vert-x3/vertx-health-check/issues/31, which was fixed in `4.2.0`.

**Comment by pmlopes** [comment] 2022-06-03 11:50
@gaol , @davidafsilva would you be interested in trying to backport it to 3.9? We are not planning any release soon, but when we do, it would include this fix.

**Comment by pmlopes** [comment] 2022-06-03 11:52
@davidafsilva if you try this, can you do it on 4.3.1? There was a bug fix with chained sub routers on that release (inheritance visibility issue), where we were down casting the routing context object, and we would stop seeing the parent base path...

**Comment by davidafsilva** [comment] 2022-06-04 11:02
@pmlopes I've opened #41 which ports your PR (#36) to the 3.9 branch. 

Regarding your last question, do you want me to test [this](https://github.com/davidafsilva/vertx-health-checks-404) with `4.3.1`? Is that it?

**Comment by pmlopes** [comment] 2022-06-04 11:22
@davidafsilva yes, just test if 4.3.1 works because I just fixed a bug recently related to sub routers and would like to be sure that it didn't introduce a regression.

Thanks!

**Comment by davidafsilva** [comment] 2022-06-04 16:57
@pmlopes 
Updated the [version](https://github.com/davidafsilva/vertx-health-checks-404/blob/61e9862f1d0129be9ef0ff93ac5d06dda11ff7a0/build.gradle.kts#L16) and the [setup](https://github.com/davidafsilva/vertx-health-checks-404/blob/61e9862f1d0129be9ef0ff93ac5d06dda11ff7a0/src/main/kotlin/pt/davidafsilva/jvm/vertx/HealthReporterVerticle.kt#L30-L35):

```shell
❯ http :49383/health
HTTP/1.1 200 OK
content-length: 70
content-type: application/json;charset=UTF-8

{
    "checks": [
        {
            "id": "dummy",
            "status": "UP"
        }
    ],
    "outcome": "UP",
    "status": "UP"
}
```

Looks good!

**Closed as completed** 2022-06-22 08:02 UTC
Labels: bug
